### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by roselidev** [Shreyz-max/Video-Captioning#4]
Hi! I appreciate your amazing work.

Your projects have a hyperlink to MSVD dataset, which already contains extracted features.

But I suspect these features are not reproducible with your current `extract_feature.py` version, since under same condition the features from downloaded dataset and ones reproduced yields different METEOR score (17.44 vs 4.06)

Are these features produced by `extract_feature.py`? If not, how can I reproduce these features?

Thank you!

**Comment by Nandini2801** [comment]
Hi! Nice work in video captioning. 
I am facing an issue with this line of code:
f = np.load(os.path.join(TRAIN_FEATURE_DIR, filename),allow_pickle=True,fix_imports=True,encoding='latin1')
I am getting error as:
Failed to interpret file 'Desktop/video_cap/MLDS_hw2_data/training_data/feat\\._-8y1Q0rA3n8_108_115.avi.npy' as a pickle
Can you help me with this issue?
Thank you

**Comment by yashnikhare22** [comment]
> Hi! Nice work in video captioning.
> I am facing an issue with this line of code:
> f = np.load(os.path.join(TRAIN_FEATURE_DIR, filename),allow_pickle=True,fix_imports=True,encoding='latin1')
> I am getting error as:
> Failed to interpret file 'Desktop/video_cap/MLDS_hw2_data/training_data/feat\._-8y1Q0rA3n8_108_115.avi.npy' as a pickle
> Can you help me with this issue?
> Thank you

Yaa I am facing same issue

**Comment by Nandini2801** [comment]
I think there is some problem with the already made numpy array file.
Actually I did got any idea to resolve the issue. But you can try creating
the numpy array files again and try again.
Hope this helps you.
If this works for you please let me know.
Regards,
Nandini Dutta

**Comment by Shreyz-max** [comment]
The problem here is while extracting the files some hidden files have also been extracted. These files are ones that start with a '.' as you can see. These hidden files are not required as we already have the same files same names that do not start with a '.' These files can be removed by using these lines of code.
`!rm training_data/video/.*.avi`
`!rm training_data/feat/.*.npy`
`!rm testing_data/video/.*.avi`
`!rm testing_data/feat/.*.npy`
This will remove all numpy arrays that start with a '.' 
I hope this clears your doubt.

**Comment by Nandini2801** [comment]
Thank you very much for your response. I will surely try out this method
and check if it is working properly and will let you know about the same.
Thanking you.
Regards,
Nandini Dutta

**Comment by yashnikhare22** [comment]
Thank you very much for sending this mail.

**Comment by roselidev** [comment]
> The problem here is while extracting the files some hidden files have also been extracted. These files are ones that start with a '.' as you can see. These hidden files are not required as we already have the same files same names that do not start with a '.' These files can be removed by using these lines of code.
> `!rm training_data/video/.*.avi`
> `!rm training_data/feat/.*.npy`
> `!rm testing_data/video/.*.avi`
> `!rm testing_data/feat/.*.npy`
> This will remove all numpy arrays that start with a '.'
> I hope this clears your doubt.

Thanks! I removed the hidden files and succeed to reproduce.
