### ISSUE TITLE
about train 

### ISSUE THREAD

**Issue by baiyunfan123** [Shreyz-max/Video-Captioning#8]
When I want to run train.py, I always report an error：
 File "D:/video-caption/code6/Video-Captioning-main/train.py", line 106, in load_dataset
    encoder_input_data.append(self.x_data[videoId[idx]])
KeyError: '1hPxGmTGarM_9_19.avi'

Please ask how to solve this problem

**Comment by NorahAbdulaziz** [comment]
I have the same issue

**Comment by Special256** [comment]
Same error, @baiyunfan123 or @NorahAbdulaziz   please share a solution if you found one.

**Comment by baiyunfan123** [comment]
Maybe the author give the training_label.josn which only has 1450 videos ,but we put 1970 videos in the train file, so the wrong number of tags and video files causes the failure. Can the author provide the correct 1450 video？

**Comment by NorahAbdulaziz** [comment]
Yeah, it would be helpful if we get these videos.

**Comment by Special256** [comment]
I actually managed to extract the 1450 videos that were used but still getting he same error.

Check out the script I used
[https://github.com/Special256/VideoCaptioning.git](url)

**Comment by Special256** [comment]
I finally got the solution to this problem.

When loading the ids from the json file, it includes the ".avi" on each id which isn't alligning to the feature_name. So I went and removed ".avi" on all ids in the json file and now I'm able to train. Please let me know if it helps.

**Comment by Special256** [comment]
I uploaded the json file at the link below, I used this with the extracted 1450 videos from the script I uploaded above.

https://github.com/Special256/VideoCaptioning/commit/85e869548ff3995d6f6e7d6cb17e3fc46302887f#commitcomment-74573701

**Comment by NorahAbdulaziz** [comment]
> I uploaded the json file at the link below, I used this with the extracted 1450 videos from the script I uploaded above.
> 
> [Special256/VideoCaptioning@85e8695#commitcomment-74573701](https://github.com/Special256/VideoCaptioning/commit/85e869548ff3995d6f6e7d6cb17e3fc46302887f#commitcomment-74573701)

thank you so much, sir. I really appreciate it.
